language: c

cache:
    directories:
        - .stack-work
        - $HOME/.stack

before_install:
    - sudo curl -sSL https://get.haskellstack.org/ | sh

install:
    - stack setup
    - stack test --only-dependencies

script:
    - stack test
